version: "3.7"

services:
  front:
    container_name: "mrb_front"
    image: node:alpine
    volumes:
      - "./front:/app"
    working_dir: /app
    entrypoint: [ "./entrypoint.sh", "npm", "run", "dev" ]

  #api:
  #  container_name: "mrb_api"
  #  image: rustlang/rust:nightly
  #  working_dir: /api
  #  volumes:
  #    - "./api:/api"
  #  command: ["./entrypoint.sh", "cargo", "run" ]
  
  api-go:
    container_name: "mrb_api_go"
    image: golang:1.13
    working_dir: /api
    volumes: 
      - "./api-go:/api"
    entrypoint: ["./entrypoint.sh", "reflex", "-c", "reflex.conf"]

  db:
    container_name: "mrb_db"
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: meeting-room-booking
    volumes:
      - "postgres:/var/lib/postgresql/data"
  
  pg-admin:
    container_name: "mrb_pgadmin"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
  
volumes:
  postgres:
