name: Api-Go

on:
  push:
    #paths:
    #  - 'api-go/*'

jobs:
  coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Action
        run: go get golang.org/x/tools/cmd/goimports && goimports -w .
