name: Api-Go

on:
  push:
    paths:
      - 'api-go/*'

jobs:
  coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        working-directory: ./api-go
        run: golint
