name: Api-Go

on:
  push:
    paths:
      - '*'

jobs:
  coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Action
        run: go get golang.org/x/tools/cmd/goimports && goimports -w .
