name: Api

on:
  [push]

jobs:
  coding-style:
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v1
        - uses: icepuma/rust-action@master
          with:
            args: cd api && cargo fmt -- --check && cargo clippy
