name: Api2

on:
  push:
    paths:
      - 'api2/*'

jobs:
  coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
      - name: Run
        working-directory: ./api2
        run: golangci-lint
